server:
  port: 80

lesson: SpringBoot

users:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 17

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root666